import rtconfig
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Glob('board.c')
src += Glob('CubeMX_Config/CM7/Src/stm32h7xx_hal_msp.c')

path = [cwd]
path += [cwd + '/CubeMX_Config/CM7/Inc']

if rtconfig.CROSS_TOOL == 'gcc':
    src += [cwd + '/CubeMX_Config/MDK-ARM/startup_stm32h747xx_CM7.s']
elif rtconfig.CROSS_TOOL == 'keil':
    src += [cwd + '/CubeMX_Config/MDK-ARM/startup_stm32h747xx_CM7.s']

# STM32H743xx || STM32H750xx || STM32F753xx
# You can select chips from the list above
CPPDEFINES = ['STM32H747xx']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
